ARG IDF_VER="v4.1"

FROM espressif/idf:${IDF_VER}

# Export cross tools directory for c-cpp-extension enhance
RUN export XTENSA_ESP32_ELF_BIN=$(dirname "$(which xtensa-esp32-elf-gcc)")
RUN export XTENSA_ESP32S2_ELF_BIN=$(dirname "$(which xtensa-esp32s2-elf-gcc)")
RUN export ESP32ULP_ELF_BIN=$(dirname "$(which esp32ulp-elf-as)")
RUN export ESP32S2ULP_ELF_BIN=$(dirname "$(which esp32s2ulp-elf-as)")

